[server]
headless = true
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 5

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#4F66DF"
backgroundColor = "#0E1420"
secondaryBackgroundColor = "#192233"
textColor = "#E8EDF5"
font = "sans serif"
